language: ruby
rvm:
- 2.0.0
script:
- bundle exec rake db:migrate --trace
- RAILS_ENV=test bundle exec rake db:migrate --trace
- bundle exec rake db:test:prepare
- bundle exec rspec -fd spec/

deploy:
  provider: heroku
  api_key:
    secure: ZCEeHx5clpFvgUwwXUHJByCgMDJtAtPuT0aq8Jv+fhSx+6IDJpfoxAk+unzLhT/DMcVwcTVEuGgf5Wzhp9uZLE+Debv0g3zyz9FDHWrP2ih/KPQwFsegNhqk357N2BX+Dkofg/xFrVbgo1wJPqLc+FuFF2w30OeOu7LDf94p/M4=
  app: recipelogger
  on:
    repo: Divinare/recipelogger
